# Generated by Django 5.1.5 on 2025-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="paid",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="specialization",
            field=models.CharField(max_length=255),
        ),
    ]
